name       : haskell-hspec
version    : 2.4.2
release    : 1
source     :
    - http://hackage.haskell.org/package/hspec-2.4.2/hspec-2.4.2.tar.gz : 48b7e342c0990ae38373acbb7cac5a2ef9b1bb2cca8bdf41a896f1593e677484
license    : MIT
component  : programming.haskell
summary    : Hspec is a testing framework for Haskell. It is inspired by the Ruby library RSpec.
description: |
    Hspec is a testing framework for Haskell. It is inspired by the Ruby library RSpec.
builddeps  :
    - haskell-cabal-install
    - haskell-hspec-core
    - haskell-hspec-discover
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
