name       : haskell-hspec
version    : 2.7.1
release    : 3
source     :
    - https://hackage.haskell.org/package/hspec-2.7.1/hspec-2.7.1.tar.gz : 818cebbcbde8761289902a816f865691e40724babf87e70057ecab204f6619f5
license    : MIT
component  : programming.haskell
summary    : Hspec is a testing framework for Haskell. It is inspired by the Ruby library RSpec.
description: |
    Hspec is a testing framework for Haskell. It is inspired by the Ruby library RSpec.
builddeps  :
    - haskell-cabal-install
    - haskell-hspec-core-devel
    - haskell-hspec-discover-devel
rundeps    :
    - devel:
        - haskell-hspec-core-devel
        - haskell-hspec-discover-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
